### ISSUE TITLE
Backend - Single event summary - view page click on the banner image then 2 banner is display on the page

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#50] opened 2022-06-16 12:13 UTC
Go to Backend  > Page > Divi builder> Select option as single event summary

Select single event from dropbox. Now click on the update button.

![image](https://user-images.githubusercontent.com/75515088/174067337-5efd0848-fb0a-479f-889e-266434ef274c.png)

Click on the view page. In the view page single event banner is display.

click on the banner image then 2 banner is display on the page

![image](https://user-images.githubusercontent.com/75515088/174067242-b04c09c7-87e1-4458-92b5-bd66aeb3665b.png)

**Comment by yukta05** [comment] 2022-06-24 07:20
The issue is solved, so i close this issue.

**Closed by yukta05** 2022-06-24 07:20 UTC
Labels: In Testing
