### ISSUE TITLE
Backend - Event listing Settings-  Order by  and order option is not working

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#48] opened 2022-06-15 06:20 UTC
Event listing Settings-  Order by  and order **(ASC/DESC)** option is not working.

I have performed below setting in the event listing but It is not working.

![image](https://user-images.githubusercontent.com/75515088/173756022-315eed9c-f14a-4514-83da-8054cdf6f271.png)

![image](https://user-images.githubusercontent.com/75515088/173756532-9597c304-ce7a-4f5c-a053-ff7b0ee5cb99.png)

**Also Select categories and type is not working. All Event are display. Selected type and categories event is not display.**

![image](https://user-images.githubusercontent.com/75515088/173757531-4e6c0bc8-4f48-4c89-a256-8add4175c1e5.png)

**Comment by yukta05** [comment] 2022-06-24 08:53
Here the issue is present. I noticed that pagination is disabled, order by:- title, order:- descending, and checked at frontend side after 10 events, it does not show descending order.

**Comment by yukta05** [comment] 2022-06-27 12:32
This issue is solved so i close this issue.

**Closed by yukta05** 2022-06-27 12:32 UTC
Labels: Fixed
