### ISSUE TITLE
Past Event listing - Events are display on the page

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wpem-divi-elements#35] opened 2021-12-20 10:14 UTC
I have  selected below event categories & type.

This event categories & type not used in the any events. After events are display on the page.

![image](https://user-images.githubusercontent.com/75515088/146751180-8fb5d2a1-b16d-4a1c-aff8-9e0e939ba6b4.png)

![image](https://user-images.githubusercontent.com/75515088/146751276-85fbc39a-49e8-4aae-9545-3bf96e49bd98.png)

**Comment by kinjal6810** [comment] 2022-06-02 07:33
Covered this issue.

**Comment by yukta05** [comment] 2022-06-07 05:47
Here selected types and categories are not displayed.
Events should be displayed as per selected types and categories,

https://user-images.githubusercontent.com/86232676/172304793-773461de-e712-49a1-9d02-20e5fe6f1c53.mp4

Need to fix this.

**Comment by yukta05** [comment] 2022-06-27 13:13
The issue is resolved. so i close this issue.

**Closed by yukta05** 2022-06-27 13:13 UTC
Labels: In Testing
